@Library('sharedlibrary@main') _

global.loadGlobalVariables()

def projectDir = "services/springboot-test/spring-boot-app"
def deploymentFilePath = "services/springboot-test/spring-boot-app-manifests/deployment.yml"

node {
    gitops.gitCheckout()
    codebuild.buildAndTest(projectDir)
    codebuild.sonarScan(projectDir)
    docker.DockerfileLinting(projectDir)
    docker.buildImage(projectDir)
    docker.ImageScan()
    docker.publishToECR()
    helmupdate.updateDeploymentFile(deploymentFilePath)
}
