@Library('sharedlibrary@main') _

global.loadGlobalVariables()

def projectDir = "services/springboot-test/spring-boot-app"
def deploymentFilePath = "services/springboot-test/spring-boot-app-manifests/deployment.yml"
def GIT_REPO_NAME = "tools"

node {
    gitops.gitCheckout()
    codebuild.buildAndTest(projectDir)
    codebuild.sonarScan(projectDir)
    dockerBuild.dockerfileLinting(projectDir)
    dockerBuild.buildImage(projectDir)
    dockerBuild.ImageScan()
    dockerBuild.publishToECR()
    helmupdate.updateDeploymentFile(deploymentFilePath,GIT_REPO_NAME)
}
